name: Makefile Output
on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker image
        run: docker build . --tag local --file .devcontainer/Dockerfile
      - name: ls
        run: ls
      - name: list docker images
        run: docker images
      - uses: docker/build-push-action@v2
        with:
          tags: local:latest
          push: false
      - uses: addnab/docker-run-action@v3
        with:
          image: local:latest
          run: echo "hello world"
#      - name: prepare output directories
#        run: |
#          for d in */; do
#            mkdir -p output/$d
#          done
#      - name: convert md to docx
#        run: |
#          find ./ -name 'Makefile' -type f -exec sh -c 'cd ${0}/.. && make BUILDDIR=/workspaces/Auto-Pandoc-Template/output github-action' {} \;
#      - uses: actions/upload-artifact@master
#        with:
#          name: output
#          path: output
