name: Makefile Output
on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker image
        run: docker build . --tag local --file .devcontainer/Dockerfile
      - name: ls
        run: ls
      - name: list docker images
        run: docker images
      - name: Run docker image
        run: docker run --name localcontainer --workdir '/workspaces/Auto-Pandoc-Template/' -d local
      - name: list docker containers
        run: docker container ls
      - name: create workdir
        run: docker exec -i localcontainer sh -c "mkdir -p /workspaces/Auto-Pandoc-Template/"
      - name: copy all to container
        run: docker cp . localcontainer:/workspaces/Auto-Pandoc-Template/.
      - name: test inside container
        run: docker exec -i localcontainer sh -c "find / -name 'essay.md'"
      - name: ls / docker
        run: docker exec -i localcontainer sh -c "ls"
      - name: prepare output directories
        run: > 
          docker exec -i localcontainer sh -c "
          for d in */; do
            mkdir -p output/$d && 'cat' > output/$d/foo.txt
          done"
      - name: test output
        run: docker exec -i localcontainer sh -c "ls output"
      - name: find all output dirs
        run: docker exec -i localcontainer sh -c "find / -name 'output'"
#      - name: convert md to docx
#        run: |
#          find ./ -name 'Makefile' -type f -exec sh -c 'cd ${0}/.. && make BUILDDIR=/workspaces/Auto-Pandoc-Template/output github-action' {} \;
      - name: copy output to host
        run: docker cp localcontainer:/workspaces/Auto-Pandoc-Template/output /output
      - uses: actions/upload-artifact@master
        with:
          name: output
          path: output
