name: Makefile Output
on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker image
        run: docker build . --tag local --file .devcontainer/Dockerfile
      - name: ls
        run: ls
      - name: list docker images
        run: docker images
      - name: Run docker image
        run: docker run --name localcontainer -d local
      - name: list docker containers
        run: docker container ls
      - name: test inside container
        run: docker exec -i localcontainer sh -c "ls && pandoc --version"
      - name: prepare output directories
        run: docker exec -i localcontainer sh -c "
          for d in */; do
            mkdir -p output/$d
          done"
#      - name: convert md to docx
#        run: |
#          find ./ -name 'Makefile' -type f -exec sh -c 'cd ${0}/.. && make BUILDDIR=/workspaces/Auto-Pandoc-Template/output github-action' {} \;
#      - uses: actions/upload-artifact@master
#        with:
#          name: output
#          path: output
